server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # =========================
            # USER SERVICE
            # =========================
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/auth/**,/api/v1/users/**

            # =========================
            # MOVIE SERVICE
            # =========================
            - id: movie-service
              uri: lb://MOVIE-SERVICE
              predicates:
                - Path=/api/v1/movies/**

            # =========================
            # THEATRE SERVICE
            # =========================
            - id: theatre-service
              uri: lb://THEATRE-SERVICE
              predicates:
                - Path=/api/v1/theatres/**,/api/v1/screens/**

            # =========================
            # BOOKING SERVICE
            # =========================
            - id: booking-service
              uri: lb://BOOKING-SERVICE
              order: 1
              predicates:
                - Path=/api/v1/bookings/**,/api/v1/holds/**,/api/v1/shows/*/seat-inventory,/api/v1/shows/*/holds

            # =========================
            # SHOW SERVICE
            # =========================
            - id: show-service
              uri: lb://SHOW-SERVICE
              order: 2
              predicates:
                - Path=/api/v1/shows/**

            # =========================
            # PAYMENT SERVICE
            # =========================
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/v1/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
